version: '3.5'
services:
  web:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
  redis:
    image: redis
    ports:
      - 6379:6379
  backend:
    image: backend
    build: ../../1/1.14/example-backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - REDIS=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=db
      - FRONT_URL=http://localhost:5000
    depends_on:
      - db
      
  frontend:
    image: frontend
    build: ../../1/1.14/example-frontend
    container_name: frontend
    ports:
      - 5000:5000
    environment:
     - API_URL=http://localhost:8000
  
    
 
      

 


