version: '3.5'

services:
  redis:
    image: redis:6.2-alpine
    command: redis-server
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
    container_name: cache

  backend:
    build: ../../1/1.14/example-backend
    container_name: backend
    ports:
      - 8080:8080
    external_links:
    - redis
    environment:
    - REDIS_HOST=redis

  frontend:
    build: ../../1/1.14/example-frontend
    container_name: frontend
    ports:
      - 5000:5000
 

