version: '3.5'
services:
  backend:
    build: ../../1/1.14/example-backend
    container_name: backend
    ports:
      - 8080:8080

  frontend:
    build: ../../1/1.14/example-frontend
    container_name: frontend
    ports:
      - 5000:5000
 

