version: '3.5'
services:
  web:
    container_name: nginx-proxy
    image: nginx
    ports:
        - 80:80
        - 8000:8000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
       - frontend
       - backend
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./database:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
  backend:
    image: backend
    build: ../../1/1.14/example-backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - REDIS=redis
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=db
      - FRONT_URL=http://localhost/
    depends_on:
      - db
      
  frontend:
    image: frontend
    build:
      context: ../../1/1.14/example-frontend
    environment:
      - API_URL=http://localhost/api
    container_name: frontend
    environment:
      - API_URL=http://localhost/api
    ports:
      - 5000:5000
    depends_on:
      - backend
  
volumes:
  database:
  
    
 
      

 


