version: '3.9'

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
  redis:
    image: redis
    ports:
      - 6379:6379
  backend:
    image: backend
    build: ../../1/1.14/example-backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - REDIS=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=db
    depends_on:
      - db
      
  frontend:
    image: frontend
    build: ../../1/1.14/example-frontend
    container_name: frontend
    ports:
      - 5000:5000
  
volumes:
  database:
